### ISSUE TITLE
Code review projektu

### ISSUE THREAD

**Issue by Willaiem** [mate966/todo-list#1]
Cześć, zobaczyłem twój post na grupce Praca w IT dla Stażystów i Juniorów (IT Jobs for Intern/Junior) i postanowiłem sprawdzić twój kod pod kątem jakości:

Ogólne:
- nazewnictwo folderów niebędące związane z danym komponentem utrzymywałbym jako małe litery.
- pliki z folderu "Images" przeniósłbym do zewnętrznego folderu o nazwie "assets", gdyż nie są bezpośrednio związane z logiką twojej aplikacji.
- zmieniłbym nazwę dla folderu "Base" na "styles". Osobiście aktualna nazwa jest dla mnie myląca, patrząc na pliki które są związane bezpośrednio z CSSem.
- unikałbym eksportowania funkcji za pomocą ``export default`` , gdyż narażasz się na potencjalne literówki. Znacznie lepszym pomysłem jest korzystanie z samego ``export``.
- mieszanie deklaracji styli wraz z komponentem nie jest dobrym pomysłem. Na przykład AppStyled przeniósłbym do osobnego pliku o nazwie App.styled.js
- Brakuje walidacji 

Działanie apki na żywo:
- Cała apka rerenderuje się, gdy dodaje/usuwam/przenoszę elementy bądź gdy przechodzę między różnymi filtrami, a to nie jest coś pożądanego. Tutaj warto popracować nad memoizacją komponentów.
- Po zakończeniu "drag and dropa" widać, że elementy są zrerenderowane w postaci takiego ćwierćsekundowego przycięcia.
- "Drag and drop" buguje się, gdy dodałem dwa elementy z tą samą nazwą.
- Gdy chcę dodać element z pustą nazwą, pojawia się alert z treścią "Inne".
- Bug - Można dodać element ze spacją.
- Gdy element jest edytowany to aktualna nazwa znika, a gdy zapiszę element z pustą nazwą to "drag and drop" na tym elemencie już nie działa.
- Przyciski do filtrowania listy nie są w jakkolwiek ostylowane, co psuje wygląd apki.
- Przycisk do akceptacji edycji mógłby być inny (ma wygląd checkboxa co jest trochę mylące), brak możliwości anulowania edycji.

App.js
- Funkcja App robi zdecydowanie za dużo rzeczy na raz. Tutaj warto zastosować wzorzec Custom Hook i rozdzielić logikę związaną z local storage do osobnego pliku.
- nie musisz deklarować funkcji w useEffectach w taki sposób. 
- nie rozumiem, po co jest tu zadeklarowany ``[input, setInput]`` - przeniósłbym to do komponentu ``Form``, który z tego korzysta.
- nazwa ``filterStatus`` jest niezrozumiała, patrząc na to że to jest są po prostu przefiltrowane zadania po statusie. Lepszą nazwą byłoby ``filteredTasks``.
- w komponentach powtarzają się niektóre propsy. Napisałeś w README, że chcesz apkę przepisać na Reduxa, ale uważam że to nie jest dobry pomysł na początku nauki Reacta. Najlepiej skorzystać z Context API, aby rozwiązać ten problem. To wbudowana funkcjonalność w Reakcie + lepiej nauczysz się jak działa taki Redux "pod spodem".

TodoList.js
- odwróciłbym warunki w  zadeklarowanym ternary operatorze. Dałoby ci to lepszą czytelność kodu.
- w handleOnDragEnd - można unikąć pierwszy splice za pomocą ``const reorderedItem = items.at(result.source.index)``

Task,js
- przyjmuje bardzo dużo propsów - tu: Context API byłoby pomocne.
- poza tym niepotrzebnie wprowadzasz ``tasks`` do propsów, gdyż setState również przyjmuje funkcję, w której znajduje się poprzedni stan. 

Form.js
- w funkcji ``handleSubmitTask`` - nie wiem po co jest wspomniany ``alert``, ale id najlepiej jest generować za pomocą biblioteki ``uuid``. Lepsze byłoby, jakby pokazywało użytkownikowi błąd.

FormStyled.js
- SubmitIcon - element "i" w HTML nie służy do określania ikon tylko kursywy. Do tego korzysta się z elementu ``span``.

Myślę też, żeby rozdzielić te elementy z FormStyled.js oraz FooterStyled.js do osobnej folderu, który mógłby się nazywać "base" i tam je trzymać. Bo inaczej to powoduje brak konsystencji i konsekwencji, na przykład w jednym komponencie użyjesz ``<p>``, a w innym własną wersję tego elementu w postaci ``<Paragraph>``. 

breakpoints.js
- niepotrzebne "zagnieźdzenie" w eksportowanym obiekcie.

Podsumowując: jeszcze dużo pracy jest przed tobą. Z pewnością warto nauczyć się takich wzorców jak Clean Code, SOLID, DRY.
Na moim profilu na GitHubie jest link do mojego Discorda - tam mogę przekazać ci wszelkie informacje o najlepszych materiałach jakie znam do nauki, abyś nie musiał popełniać tych samych błędów jak ja.
Akurat szukam osób, które byłyby chętne do rozwijanie wspólnie projektu/aplikacji, którą można wrzucić sobie do portfolio, która by przekuwała oko rekruterów i osób technicznych. 
Daje konstruktywny feedback, tak jak teraz sprawdzam kod pod kątem jakości, aby dana osoba rozwijała się znacznie szybciej niż jakby robiła to wszystko sama.

Pozdrawiam!

**Comment by mate966** [comment]
Hej!  Ogromne dzięki za feedback! Postaram się wszystko poprawić i odezwać po wszystkim. Aktualnie mam kilka rozmów o pracę, kursy i co chwila jakieś testy i zadania na interview do oddania więc głównie na tym się teraz skupiam, a moje starsze projekty odeszły trochę na bok… ale na pewno nie w zapomnienie!. Człowiek myśli, że jest fajnie, pięknie i nie ma tragedii, a tutaj taka bomba z poprawkami :D  Jeszcze raz Wielkie Dziękuje!   Pozdrawiam!   Cześć, zobaczyłem twój post na grupce Praca w IT dla Stażystów i Juniorów (IT Jobs for Intern/Junior) i postanowiłem sprawdzić twój kod pod kątem jakości: Ogólne: nazewnictwo folderów niebędące związane z danym komponentem utrzymywałbym jako małe litery. pliki z folderu &#34;Images&#34; przeniósłbym do zewnętrznego folderu o nazwie &#34;assets&#34;, gdyż nie są bezpośrednio związane z logiką twojej aplikacji. zmieniłbym nazwę dla folderu &#34;Base&#34; na &#34;styles&#34;. Osobiście aktualna nazwa jest dla mnie myląca, patrząc na pliki które są związane bezpośrednio z CSSem. unikałbym eksportowania funkcji za pomocą  export default  , gdyż narażasz się na potencjalne literówki. Znacznie lepszym pomysłem jest korzystanie z samego  export . mieszanie deklaracji styli wraz z komponentem nie jest dobrym pomysłem. Na przykład AppStyled przeniósłbym do osobnego pliku o nazwie App.styled.js Brakuje walidacji Działanie apki na żywo: Cała apka rerenderuje się, gdy dodaje/usuwam/przenoszę elementy bądź gdy przechodzę między różnymi filtrami, a to nie jest coś pożądanego. Tutaj warto popracować nad memoizacją komponentów. Po zakończeniu &#34;drag and dropa&#34; widać, że elementy są zrerenderowane w postaci takiego ćwierćsekundowego przycięcia. &#34;Drag and drop&#34; buguje się, gdy dodałem dwa elementy z tą samą nazwą. Gdy chcę dodać element z pustą nazwą, pojawia się alert z treścią &#34;Inne&#34;. Bug - Można dodać element ze spacją. Gdy element jest edytowany to aktualna nazwa znika, a gdy zapiszę element z pustą nazwą to &#34;drag and drop&#34; na tym elemencie już nie działa. Przyciski do filtrowania listy nie są w jakkolwiek ostylowane, co psuje wygląd apki. Przycisk do akceptacji edycji mógłby być inny (ma wygląd checkboxa co jest trochę mylące), brak możliwości anulowania edycji. App.js Funkcja App robi zdecydowanie za dużo rzeczy na raz. Tutaj warto zastosować wzorzec Custom Hook i rozdzielić logikę związaną z local storage do osobnego pliku. nie musisz deklarować funkcji w useEffectach w taki sposób. nie rozumiem, po co jest tu zadeklarowany  [input, setInput]  - przeniósłbym to do komponentu  Form , który z tego korzysta. nazwa  filterStatus  jest niezrozumiała, patrząc na to że to jest są po prostu przefiltrowane zadania po statusie. Lepszą nazwą byłoby  filteredTasks . w komponentach powtarzają się niektóre propsy. Napisałeś w README, że chcesz apkę przepisać na Reduxa, ale uważam że to nie jest dobry pomysł na początku nauki Reacta. Najlepiej skorzystać z Context API, aby rozwiązać ten problem. To wbudowana funkcjonalność w Reakcie + lepiej nauczysz się jak działa taki Redux &#34;pod spodem&#34;. TodoList.js odwróciłbym warunki w  zadeklarowanym ternary operatorze. Dałoby ci to lepszą czytelność kodu. w handleOnDragEnd - można unikąć pierwszy splice za pomocą  const reorderedItem = items.at(result.source.index) Task,js przyjmuje bardzo dużo propsów - tu: Context API byłoby pomocne. poza tym niepotrzebnie wprowadzasz  tasks  do propsów, gdyż setState również przyjmuje funkcję, w której znajduje się poprzedni stan. Form.js w funkcji  handleSubmitTask  - nie wiem po co jest wspomniany  alert , ale id najlepiej jest generować za pomocą biblioteki  uuid . Lepsze byłoby, jakby pokazywało użytkownikowi błąd. FormStyled.js SubmitIcon - element &#34;i&#34; w HTML nie służy do określania ikon tylko kursywy. Do tego korzysta się z elementu  span . Myślę też, żeby rozdzielić te elementy z FormStyled.js oraz FooterStyled.js do osobnej folderu, który mógłby się nazywać &#34;base&#34; i tam je trzymać. Bo inaczej to powoduje brak konsystencji i konsekwencji, na przykład w jednym komponencie użyjesz  &lt;p&gt; , a w innym własną wersję tego elementu w postaci  &lt;Paragraph&gt; . breakpoints.js niepotrzebne &#34;zagnieźdzenie&#34; w eksportowanym obiekcie. Podsumowując: jeszcze dużo pracy jest przed tobą. Z pewnością warto nauczyć się takich wzorców jak Clean Code, SOLID, DRY.  Na moim profilu na GitHubie jest link do mojego Discorda - tam mogę przekazać ci wszelkie informacje o najlepszych materiałach jakie znam do nauki, abyś nie musiał popełniać tych samych błędów jak ja.  Akurat szukam osób, które byłyby chętne do rozwijanie wspólnie projektu/aplikacji, którą można wrzucić sobie do portfolio, która by przekuwała oko rekruterów i osób technicznych.  Daje konstruktywny feedback, tak jak teraz sprawdzam kod pod kątem jakości, aby dana osoba rozwijała się znacznie szybciej niż jakby robiła to wszystko sama. Pozdrawiam! —  Reply to this email directly,  github.com view it on GitHub , or  github.com unsubscribe .  You are receiving this because you are subscribed to this thread. Message ID:  &lt;mate966/todo-list/issues/1 @ github . com&gt;
